import { useEffect, useState } from 'react'
import { WORKFLOW_NODES } from './workflow.js'

const EFFORTS = ['medium', 'high', 'xhigh']
function editable(config) { return { declaration_context: config.declaration_context ? { ...config.declaration_context } : null, pool: config.pool.map(({ id, efforts }) => ({ id, efforts: [...efforts] })), mode: config.mode, bootstrap: { ...config.bootstrap }, role_models: { ...config.effective_models }, role_efforts: { ...config.effective_efforts } } }
export function ModelSettings({ config, busy, onSave, onAllocate }) {
  const [draft, setDraft] = useState(() => editable(config))
  const [dirty, setDirty] = useState(false)
  useEffect(() => { if (!dirty) setDraft(editable(config)) }, [config, dirty])
  const update = (next) => { setDirty(true); setDraft(next) }
  const effortsFor = (id) => draft.pool.find((entry) => entry.id === id)?.efforts || []
  const choices = (selected) => <>{!draft.pool.some(({ id }) => id === selected) && <option value={selected}>{selected || '请选择模型'} · 不在当前池中</option>}{draft.pool.map(({ id }, index) => <option key={index} value={id}>{id || '待填写 ID'}</option>)}</>
  const effortChoices = (model, selected) => <>{!effortsFor(model).includes(selected) && <option value={selected}>{selected || '请选择 effort'} · 需修正</option>}{effortsFor(model).map((effort) => <option key={effort}>{effort}</option>)}</>
  const save = async () => {
    const input = { ...(draft.declaration_context ? { declaration_context: draft.declaration_context.id } : {}), pool: draft.pool, mode: draft.mode, bootstrap: draft.bootstrap, ...(draft.mode === 'manual' ? { role_models: draft.role_models, role_efforts: draft.role_efforts } : {}) }
    const result = await onSave(input)
    if (result) { setDraft(editable(result)); setDirty(false) }
  }
  const targetChanged = dirty && draft.declaration_context?.id !== config.declaration_context?.id
  const targetLabel = (context) => context?.kind === 'unbound' ? '首次连接前的声明，将绑定随后保存的连接' : `${context?.kind === 'pending_catalog' ? '本次检测的待连接服务' : '当前连接'} · ${context?.protocol || ''} · ${context?.endpoint || ''}`
  return <section className="model-settings"><div className="section-heading"><h2>模型分配</h2><span className="save-state">{dirty ? '未保存' : config.allocation_state === 'ready' ? '已就绪' : config.allocation_state === 'pending' ? '待主 Agent 分配' : '手动选择需修正'}</span></div>
    <p className="field-note">本次能力声明对应：{targetLabel(draft.declaration_context)}</p>
    {targetChanged && <div role="alert"><p className="form-error">声明目标已变化，当前草稿仍对应原目标。请重新检测目标连接，再确认新的声明对象。</p><p className="field-note">当前可确认：{targetLabel(config.declaration_context)}</p><button type="button" className="quiet-action" disabled={busy || !config.declaration_context} onClick={() => update({ ...draft, declaration_context: { ...config.declaration_context } })}>确认当前声明目标</button></div>}
    <p className="field-note">自定义模型和 effort 表示你声明 API 服务支持这些选择；实际网关尚未验证。未知模型的上下文和价格保持未知。</p>
    <details><summary>Anthropic Messages 可选模型与 effort</summary><p className="field-note">以下能力来自固定 SDK 目录。请将所需模型加入模型池，勾选列出的 effort，再明确选择主模型。此协议不接受其他模型或推理强度。</p><dl>{(config.protocol_models || []).map(({ id, efforts }) => <div key={id}><dt>{id}</dt><dd>{efforts.join(' · ')}</dd></div>)}</dl></details>
    <label>分配模式<select value={draft.mode} disabled={busy} onChange={(event) => update({ ...draft, mode: event.target.value })}><option value="auto">自动 · 主 Agent 分配</option><option value="manual">手动 · 逐个 Agent 选择</option></select></label>
    <fieldset><legend>可用模型池</legend>{draft.pool.map((entry, index) => <div className="pool-entry" key={index}><label>模型 ID<input value={entry.id} maxLength={96} disabled={busy} spellCheck="false" list="known-models" onChange={(event) => update({ ...draft, pool: draft.pool.map((item, at) => at === index ? { ...item, id: event.target.value } : item) })} /></label><div className="effort-options">{EFFORTS.map((effort) => <label key={effort}><input type="checkbox" checked={entry.efforts.includes(effort)} disabled={busy} onChange={(event) => update({ ...draft, pool: draft.pool.map((item, at) => at === index ? { ...item, efforts: event.target.checked ? [...item.efforts, effort] : item.efforts.filter((value) => value !== effort) } : item) })} />{effort}</label>)}</div><button className="quiet-action" type="button" disabled={busy || draft.pool.length === 1} onClick={() => update({ ...draft, pool: draft.pool.filter((_, at) => at !== index) })}>移除模型</button></div>)}<button type="button" className="quiet-action" disabled={busy || draft.pool.length >= 12} onClick={() => update({ ...draft, pool: [...draft.pool, { id: '', efforts: [] }] })}>添加模型</button><datalist id="known-models">{config.known_models.map((id) => <option key={id} value={id} />)}</datalist></fieldset>
    <fieldset><legend>用于首次分配的主模型</legend><label>主模型<select value={draft.bootstrap.model} disabled={busy} onChange={(event) => update({ ...draft, bootstrap: { model: event.target.value, effort: effortsFor(event.target.value).includes(draft.bootstrap.effort) ? draft.bootstrap.effort : '' } })}>{choices(draft.bootstrap.model)}</select></label><label>effort<select value={draft.bootstrap.effort} disabled={busy} onChange={(event) => update({ ...draft, bootstrap: { ...draft.bootstrap, effort: event.target.value } })}>{effortChoices(draft.bootstrap.model, draft.bootstrap.effort)}</select></label><p className="field-note">可先保存模型池，再填写 API 连接。分配未完成时用此模型聊天；完成后使用流程编排 Agent。</p></fieldset>
    {draft.mode === 'manual' && <fieldset><legend>手动角色选择</legend>{WORKFLOW_NODES.map(({ role, name }) => <div className="manual-role" key={role}><strong>{name}</strong><label>模型<select value={draft.role_models[role]} disabled={busy} onChange={(event) => update({ ...draft, role_models: { ...draft.role_models, [role]: event.target.value }, role_efforts: { ...draft.role_efforts, [role]: effortsFor(event.target.value).includes(draft.role_efforts[role]) ? draft.role_efforts[role] : '' } })}>{choices(draft.role_models[role])}</select></label><label>effort<select value={draft.role_efforts[role]} disabled={busy} onChange={(event) => update({ ...draft, role_efforts: { ...draft.role_efforts, [role]: event.target.value } })}>{effortChoices(draft.role_models[role], draft.role_efforts[role])}</select></label></div>)}</fieldset>}
    <div className="action-row"><button type="button" className="primary-action" disabled={busy || !dirty} onClick={save}>保存模型配置</button><button type="button" className="quiet-action" disabled={busy || dirty || config.mode !== 'auto'} onClick={onAllocate}>主 Agent 分配</button></div>
    <p className="field-note">{config.mode === 'manual' ? '手动模式不会被主 Agent 自动覆盖。' : '模型池或目标变化后可请求重新分配；每次运行不会额外触发分配。'} {config.draft_notice}</p>
    <h3>当前实际分配</h3><p className="field-note">来源：{({ default: '固定默认配置', agent: '主 Agent 的分配', user: '用户保存', conversation: '对话中的明确调整' })[config.allocation_source]}</p><dl className="saved-models">{WORKFLOW_NODES.map(({ role, name }) => <div key={role}><dt>{name}</dt><dd>{config.effective_models[role]} · {config.effective_efforts[role]}{config.allocation_reasons[role] && <p>{config.allocation_reasons[role]}</p>}</dd></div>)}</dl><dl>{config.pool_metadata.map((entry) => <div key={entry.id}><dt>{entry.id}</dt><dd>{({ user_declared: '用户声明', host_catalog: '本机目录元数据', pinned_sdk: '固定 SDK 元数据' })[entry.source]} · 网关未验证</dd></div>)}</dl>
  </section>
}
