# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.

"""Generate the TypeScript OpenJiuwen trajectory semantic constants.

The upstream GenAI registry is generated by ``generate.py``. This script covers
the project's own extensions, whose single source is Agent Core:

* every ``OJ_*`` / ``AT_*`` / ``DA_*`` attribute key in
  ``openjiuwen/extensions/observability/semconv.py``;
* the closed ``TRAJECTORY_RECORD_KINDS`` / ``TRAJECTORY_EVENT_KINDS`` sets and
  ``TRAJECTORY_SPAN_SCHEMA_VERSION``;
* the ``@oj-seq`` reference format in ``content_addressing.py``.

The modules are read with ``ast`` rather than imported, so this runs offline
and without Agent Core's runtime dependencies.
"""

from __future__ import annotations

import argparse
import ast
import difflib
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SWARM_ROOT = SCRIPT_DIR.parents[1]
TS_OUTPUT = (
    SWARM_ROOT
    / "jiuwenswarm/channels/web/frontend/src/features/trajectory/semconv"
    / "openjiuwen-semconv.generated.ts"
)
SEMCONV_RELATIVE = Path("openjiuwen/extensions/observability/semconv.py")
CONTENT_ADDRESSING_RELATIVE = Path("openjiuwen/extensions/observability/content_addressing.py")

_KEY_PREFIXES = {
    "OJ_": ("openjiuwen.",),
    "AT_": ("agentteam.",),
    "DA_": ("deepagent.",),
}
_TUPLE_CONSTANTS = ("TRAJECTORY_RECORD_KINDS", "TRAJECTORY_EVENT_KINDS")
_SCALAR_CONSTANTS = ("TRAJECTORY_SPAN_SCHEMA_VERSION",)
_SEQUENCE_CONSTANTS = ("SEQUENCE_REFERENCE_PREFIX", "SEQUENCE_REFERENCE_VERSION")


def _module_constants(path: Path) -> dict[str, str | tuple[str, ...]]:
    """Return module-level string and string-tuple assignments, in order."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    constants: dict[str, str | tuple[str, ...]] = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target, value = node.targets[0], node.value
        elif isinstance(node, ast.AnnAssign) and node.value is not None:
            target, value = node.target, node.value
        else:
            continue
        if not isinstance(target, ast.Name):
            continue
        if isinstance(value, ast.Constant) and isinstance(value.value, str):
            constants[target.id] = value.value
        elif isinstance(value, ast.Tuple) and all(
            isinstance(item, ast.Constant) and isinstance(item.value, str) for item in value.elts
        ):
            constants[target.id] = tuple(item.value for item in value.elts)  # type: ignore[attr-defined]
    return constants


def _require(constants: dict[str, str | tuple[str, ...]], name: str, kind: type, path: Path):
    value = constants.get(name)
    if not isinstance(value, kind):
        raise ValueError(f"{name} missing or not a {kind.__name__} in {path}")
    return value


def _extract(agent_core_dir: Path) -> tuple[dict[str, str], dict[str, tuple[str, ...]], dict[str, str]]:
    semconv_path = agent_core_dir / SEMCONV_RELATIVE
    addressing_path = agent_core_dir / CONTENT_ADDRESSING_RELATIVE
    semconv = _module_constants(semconv_path)
    addressing = _module_constants(addressing_path)

    keys: dict[str, str] = {}
    for name, value in semconv.items():
        for prefix, value_prefixes in _KEY_PREFIXES.items():
            if name.startswith(prefix) and isinstance(value, str) and value.startswith(value_prefixes):
                keys[name] = value
    if not keys:
        raise ValueError(f"no project attribute keys found in {semconv_path}")
    duplicates = {value for value in keys.values() if list(keys.values()).count(value) > 1}
    if duplicates:
        raise ValueError(f"attribute keys defined more than once: {sorted(duplicates)}")

    sets = {name: _require(semconv, name, tuple, semconv_path) for name in _TUPLE_CONSTANTS}
    scalars = {name: _require(semconv, name, str, semconv_path) for name in _SCALAR_CONSTANTS}
    scalars.update({name: _require(addressing, name, str, addressing_path) for name in _SEQUENCE_CONSTANTS})
    return keys, sets, scalars


def _ts_string(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _render_typescript(
    keys: dict[str, str],
    sets: dict[str, tuple[str, ...]],
    scalars: dict[str, str],
) -> str:
    lines = [
        "// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.",
        "",
        "/**",
        " * Generated OpenJiuwen trajectory semantic conventions.",
        " *",
        " * Source: agent-core openjiuwen/extensions/observability/semconv.py and",
        " * content_addressing.py. Do not edit by hand; run `make openjiuwen-semconv`.",
        " * Viewer aliases over these values belong in constants.ts.",
        " */",
        "",
    ]
    lines.extend(f"export const {name} = {_ts_string(value)} as const" for name, value in scalars.items())
    lines.extend(["", "export const OPENJIUWEN_SEMCONV = {"])
    lines.extend(f"  {name}: {_ts_string(value)}," for name, value in keys.items())
    lines.extend(["} as const", ""])
    for name, values in sets.items():
        lines.append(f"export const {name} = [")
        lines.extend(f"  {_ts_string(value)}," for value in values)
        lines.extend(["] as const", ""])
    return "\n".join(lines)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--agent-core-dir",
        type=Path,
        default=SWARM_ROOT.parent / "agent-core",
        help="path to the agent-core checkout",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the generated output differs without writing it",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    agent_core_dir = args.agent_core_dir.expanduser().resolve()
    if not (agent_core_dir / SEMCONV_RELATIVE).is_file():
        raise FileNotFoundError(f"agent-core checkout not found: {agent_core_dir}")
    keys, sets, scalars = _extract(agent_core_dir)
    expected = _render_typescript(keys, sets, scalars)
    actual = TS_OUTPUT.read_text(encoding="utf-8") if TS_OUTPUT.exists() else ""
    summary = f"{len(keys)} keys, " + ", ".join(f"{len(v)} {k.lower()}" for k, v in sets.items())
    if args.check:
        if actual == expected:
            print(f"OpenJiuwen semantic-convention output is current: {summary}.")
            return 0
        print(
            "".join(
                difflib.unified_diff(
                    actual.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=str(TS_OUTPUT),
                    tofile=f"{TS_OUTPUT} (generated)",
                )
            ),
            end="",
        )
        print("OpenJiuwen semantic-convention output is out of date.")
        return 1
    if actual != expected:
        temporary = TS_OUTPUT.with_name(f".{TS_OUTPUT.name}.tmp")
        temporary.write_text(expected, encoding="utf-8")
        temporary.replace(TS_OUTPUT)
        print(f"Updated {TS_OUTPUT}")
    else:
        print("OpenJiuwen semantic-convention output was already current.")
    print(f"Generated {summary}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
