# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.

"""Proactive engine — service that scans user conversations, updates the user
profile, and decides whether to proactively reach out with a skill recommendation,
task reminder, or need exploration message.

This is a pure service class that responds to external calls (from CronScheduler
or manual triggers). It does NOT run its own background tick loop.

Runs in AgentServer process. Decision is made by a proactive lightweight agent
(``set_proactive_agent``); the recommendation message is generated by the main
agent — tick triggers it via ``set_trigger_main_agent_callback``, so the message
naturally enters the main agent's context engine and streams to the frontend.

Usage:
- ``engine = ProactiveEngine(config)``
- ``engine.set_proactive_agent(proactive_agent)``
- ``engine.set_trigger_main_agent_callback(callback)``
- ``await engine.tick_now()`` — trigger a recommendation tick
"""

from __future__ import annotations

import logging
import re
import time
import uuid

from typing import Any

logger = logging.getLogger(__name__)


# proactive 数值配置项的合法区间（与 web handler _validate_proactive_int 保持一致）。
_PROACTIVE_INT_LO = 1
_PROACTIVE_INT_HI = 50


def _safe_proactive_int(val: Any, default: int) -> int:
    """读取 proactive 数值配置项的防御性解析。

    config.yaml 被手改成非数字/浮点/超范围时，降级用 default + warning，不让引擎崩溃。
    （handler 写入时已校验，这里只防手改 config / 旧脏数据。）
    """
    # 先按字符串校验：挡住浮点(3.5)、科学计数(1e5)、字符串(abc)、空。
    # int(3.5) 在 Python 会静默截断成 3，不能直接 int()。
    raw = str(val).strip() if val is not None else ""
    if not re.fullmatch(r"[0-9]+", raw):
        logger.warning(
            "[ProactiveEngine] invalid int config %r, fallback to default %d", val, default,
        )
        return default
    n = int(raw)
    if n < _PROACTIVE_INT_LO or n > _PROACTIVE_INT_HI:
        logger.warning(
            "[ProactiveEngine] int config %r out of [%d,%d], fallback to default %d",
            val, _PROACTIVE_INT_LO, _PROACTIVE_INT_HI, default,
        )
        return default
    return n


class ProactiveEngine:
    """Proactive recommendation engine service.

    Each tick:
    1. Build a situation report from multi-session history + profile
    2. Single LLM call (via proactive agent): update profile + decide recommendation type
    3. If a decision is made: trigger main agent to generate message → streams to frontend
       (message naturally enters the main agent's context engine)

    This class does NOT run its own background loop. It is triggered by:
    - CronScheduler (via proactive.tick WebSocket request from Gateway),
      including the "run now" button in the Cron panel (also goes through
      proactive.tick — no separate manual-trigger endpoint).
    """

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        config = config or {}
        self._max_per_day: int = _safe_proactive_int(config.get("max_recommend_per_day", 5), 5)
        self._max_rounds: int = _safe_proactive_int(config.get("max_rounds_per_tick", 20), 20)
        # 默认 False，与 config.yaml 的 proactive_recommendation.enabled 默认值一致，
        # 防御性默认=关闭，避免配置段缺失时引擎被误启用。
        self._enabled: bool = config.get("enabled", False)
        self._last_tick_at: float = 0.0
        # 推荐专用 agent：只做决策（无 session、无 tools、单轮、输出 JSON），
        # 替代 proactive_actions._analyze_and_decide 里的裸 model.invoke。
        self._proactive_agent: Any = None
        # 触发主 agent 跑一轮生成话术的回调。
        self._trigger_main_agent_callback: Any = None
        # 检查目标 channel 是否有活跃 agent（避免 agent 被 evict 后白调 LLM）。
        self._check_agent_available_callback: Any = None
        # 推送通知回调——直接推一条文本到前端，不经过主 agent（不进 context）。
        # 用于"今日推荐已达上限"等系统提醒。
        self._send_notification_callback: Any = None

    def set_proactive_agent(self, agent: Any) -> None:
        """Set the proactive lightweight agent used for recommendation decision.

        Args:
            agent: A DeepAgent instance (no tools, no task_loop, single-round).
                   Built by app_agentserver via create_deep_agent.
        """
        self._proactive_agent = agent

    @property
    def last_tick_at(self) -> float:
        """Last tick timestamp (public read accessor for ``_last_tick_at``)."""
        return self._last_tick_at

    def rebuild_proactive_agent(self, builder: Any) -> None:
        """Rebuild the proactive agent (e.g. after model config changed).

        The proactive agent is built once at AgentServer startup with the then-
        current model config. When the user changes models (frontend config
        save → agent.reload_config), the main agents hot-reload, but the
        proactive agent would keep the stale model. Call this to rebuild it
        with the latest model config.

        Args:
            builder: Callable ``() -> DeepAgent | None`` (the proactive_adapter
                     ``build_proactive_agent``), re-reads model config at call.
        """
        try:
            new_agent = builder()
            if new_agent is not None:
                self._proactive_agent = new_agent
                logger.info("[ProactiveEngine] proactive agent rebuilt (model config refreshed)")
        except Exception as exc:
            logger.warning("[ProactiveEngine] proactive agent rebuild failed: %s", exc)

    def set_trigger_main_agent_callback(self, callback: Any) -> None:
        """Set the callback that triggers the main agent to run one round."""
        self._trigger_main_agent_callback = callback

    def set_check_agent_available_callback(self, callback: Any) -> None:
        """Set the callback that checks if the target channel has an active agent."""
        self._check_agent_available_callback = callback

    def set_send_notification_callback(self, callback: Any) -> None:
        """Set the callback for pushing a simple text notification (no LLM, no context).

        用于"今日推荐已达上限"等系统提醒——直接推文本到前端，不触发主 agent。
        """
        self._send_notification_callback = callback

    def reload_config(self, config: dict[str, Any]) -> None:
        """Hot-reload configuration without restarting the process."""
        new_enabled = bool(config.get("enabled", False))
        new_max_per_day = _safe_proactive_int(config.get("max_recommend_per_day", self._max_per_day), self._max_per_day)
        new_max_rounds = _safe_proactive_int(config.get("max_rounds_per_tick", self._max_rounds), self._max_rounds)

        # 当日推荐计数 _daily_counts 不重置——它是"今天实际推了几条"的客观事实，清掉反而会让
        # 调小上限时 count 归零 < 新上限，在已超额的情况下继续推送，违反上限语义。
        # 上限提醒已改为前端弹窗 + 每次命中都推，无需清任何去重标记。

        self._max_per_day = new_max_per_day
        self._max_rounds = new_max_rounds
        self._enabled = new_enabled
        logger.info("[ProactiveEngine] config reloaded (enabled=%s, max_per_day=%d)",
                   new_enabled, new_max_per_day)

    async def tick_now(
        self,
        target_channel: str | None = None,
    ) -> bool:
        """Trigger a recommendation tick.

        This is the main API for external callers (CronScheduler, manual triggers).

        Args:
            target_channel: Optional channel ID to deliver the recommendation to.
                          If None, uses the most recently active session.

        Returns:
            True if a recommendation was made, False otherwise.
        """
        if not self._enabled:
            logger.debug("[ProactiveEngine] engine disabled, skipping tick")
            return False

        logger.info("[ProactiveEngine] tick_now called (target_channel=%s)", target_channel)
        try:
            pushed = await self._tick(target_channel=target_channel)
            return bool(pushed)
        except Exception as exc:
            logger.warning("[ProactiveEngine] tick_now failed: %s", exc, exc_info=True)
            return False

    async def _tick(self, target_channel: str | None = None) -> bool:
        """Single tick: build situation → analyze → push.

        Args:
            target_channel: Optional channel ID to deliver the recommendation to.
                          If None, uses the most recently active session.

        Returns:
            True if a recommendation was actually pushed to the channel,
            False if the tick was skipped for any reason (daily limit reached,
            empty situation, no model, no decision, no delivery
            target). Callers (CronScheduler / manual trigger) should use this
            to report an accurate status instead of assuming "sent".
        """
        from jiuwenswarm.agents.harness.common.recommendation.proactive_actions import (
            _today_recommend_count,
            _increment_daily_count,
            _get_all_skills,
            _analyze_and_decide,
            _trigger_main_agent,
        )
        from jiuwenswarm.agents.harness.common.recommendation.profile_extractor import (
            load_recommendation_state,
            save_recommendation_state,
        )
        from jiuwenswarm.agents.harness.common.recommendation.situation_report import (
            build_situation_report,
        )

        # 每次 tick 顺手清理过期数据（daily_counts 老日期 key、cooldown_records 过期项）。
        try:
            self.run_maintenance()
        except Exception as exc:
            logger.debug("[ProactiveEngine] maintenance failed: %s", exc)

        # 本 tick 的语言基准：config.yaml preferred_language，决策/指令/梯度渲染共用，
        # 与正常聊天的回复语言同源（改设置即时生效）。
        from jiuwenswarm.common.config import get_config
        preferred_language = str(get_config().get("preferred_language") or "zh")

        # Step 0: 检查目标 channel 是否有活跃 agent——agent 被 evict 后白调 LLM 是浪费 token。
        if self._check_agent_available_callback is not None:
            try:
                if not self._check_agent_available_callback(target_channel):
                    logger.debug("[ProactiveEngine] no active agent for channel=%s, skipping tick", target_channel)
                    self._last_tick_at = time.time()
                    return False
            except Exception as exc:
                logger.debug("[ProactiveEngine] check_agent_available failed: %s", exc)

        # Gate: daily budget
        if _today_recommend_count() >= self._max_per_day:
            logger.info("[ProactiveEngine] daily limit reached (%d/%d), skipping tick",
                       _today_recommend_count(), self._max_per_day)
            # 推送通知提醒用户已到上限。前端拦截 source=proactive_notification 后改走
            # 顶部弹窗（不进会话历史），故这里每次命中上限都推一次，无需去重。
            if self._send_notification_callback is not None:
                try:
                    await self._send_notification_callback(
                        target_channel,
                        f"今日主动推荐已达每日上限（{self._max_per_day} 条），"
                        f"明日恢复。",
                    )
                except Exception as exc:
                    logger.debug("[ProactiveEngine] send_notification failed: %s", exc)
            self._last_tick_at = time.time()
            return False

        # ── Step 1: Build situation report ─────────────────────
        _, available_skills = _get_all_skills()
        report = await build_situation_report(
            max_rounds=self._max_rounds,
            skills=available_skills,
        )

        if report.is_empty():
            logger.debug("[ProactiveEngine] situation report empty, skipping tick")
            self._last_tick_at = time.time()
            return False

        report_text = report.render_for_llm()

        # ── Step 1.5: Consume feedback buffer → update gradients ──
        state = load_recommendation_state()
        if state.feedback_buffer and self._proactive_agent is not None:
            try:
                from jiuwenswarm.agents.harness.common.recommendation.feedback_collector import (
                    consume_feedback_buffer,
                )
                from jiuwenswarm.agents.harness.common.recommendation.gradient_updater import (
                    update_gradients,
                )

                feedbacks = consume_feedback_buffer(state)
                if feedbacks:
                    updated = await update_gradients(
                        feedbacks, state.strategy_gradients, self._proactive_agent,
                    )
                    # 留最新 20 条：截断方向反映"保留最近反馈学到的梯度"。revise 挪位
                    # （apply_operations）+ 留最新配合 → 被新反馈更新/新增的规则优先保留，
                    # 早期未被触及的规则优先淘汰（LRU 语义）。容量 20 与喂 LLM 的决策层
                    # 10 + 话术层 10 = 20 一致，存储满载时喂 LLM 也能取满。
                    state.strategy_gradients = updated[-20:]  # Limit to 20 gradients
                    state.touch()
                    save_recommendation_state(state)
                    logger.info("[ProactiveEngine] updated %d gradients from %d feedbacks",
                                len(updated), len(feedbacks))
            except Exception as exc:
                logger.warning("[ProactiveEngine] gradient update failed: %s", exc, exc_info=True)

        # ── Step 2: LLM analysis + decision ────────────────────
        if self._proactive_agent is None:
            logger.debug("[ProactiveEngine] no proactive agent available, skipping tick")
            self._last_tick_at = time.time()
            return False

        # Build decision rules from gradients (gradient attribution)
        from jiuwenswarm.agents.harness.common.recommendation.gradient_updater import (
            render_decision_rules,
        )
        decision_rules_text = render_decision_rules(
            state.strategy_gradients,
            language=preferred_language,
        )

        result = await _analyze_and_decide(
            report_text, available_skills, self._proactive_agent,
            decision_rules_text=decision_rules_text,
            language=preferred_language,
        )

        # ── Step 3: Check if we have a recommendation ───────────
        decision = result.decision
        if not decision:
            logger.debug("[ProactiveEngine] no recommendation this tick")
            self._last_tick_at = time.time()
            return False

        # ── Step 4: (removed) Cooldown check ──────────────────
        # 原来用 cooldown_records 做字面精确去重（同 target 24h 不推），但这对三类推荐
        # 语义都是错配：skill 同名不同事可再推（误杀）、task 未闭环该再提醒（误杀）、
        # exploration 字面不同换皮又挡不住（漏放）。去重改由决策 LLM 承担——历史推荐
        # 记录（type/target/reason）已喂进决策 prompt 当硬约束，LLM 决策时即跳过已推。
        # 假送达连推（bug A）已由 _push_chunks 识别 chat.error 不调 on_delivered 堵住，
        # 并发由 _proactive_push_inflight 去重，总量由 max_recommend_per_day 限。cooldown
        # 不再有独立价值，移除 gate；cooldown_records 字段保留但不再作 gate、不再写入。

        # ── Step 5: Pick delivery target ───────────────────────
        # 两种触发（cron 自然到点 / Cron 面板"立即执行"）统一：都用"最活跃会话"。
        # find_session_for_channel / most_recent_active_session 的选法已修：不再要求历史
        # 完整、_scan_sessions 走缓存拿最新 last_message_at，故刚发消息、assistant 还没
        # 回完的当前会话也能被准确选为最活跃会话。
        if target_channel:
            target_session = report.find_session_for_channel(target_channel)
            if not target_session:
                logger.debug("[ProactiveEngine] no session found for channel '%s'", target_channel)
                self._last_tick_at = time.time()
                return False
        else:
            target_session = report.most_recent_active_session()
            if not target_session:
                logger.debug("[ProactiveEngine] no active session for delivery")
                self._last_tick_at = time.time()
                return False

        # ── Step 6: Trigger main agent to generate & deliver ────
        # fire-and-forget：trigger_main_agent 把主 agent 跑一轮丢后台 task，立即返回
        # True（表示"已触发"），让调用方 cron 秒回不超时。Step 7 的状态更新不在
        # 这里立即做，而是包成 on_delivered 回调——后台 task 真正跑完、推荐确实送达
        # 后才回调执行计数/持久化，避免"触发即计数、后台失败却已计数"的名不副实。
        if self._trigger_main_agent_callback is None:
            logger.warning("[ProactiveEngine] no trigger_main_agent_callback, skipping")
            self._last_tick_at = time.time()
            return False

        # Build style rules from gradients (gradient attribution)
        from jiuwenswarm.agents.harness.common.recommendation.gradient_updater import (
            render_style_rules,
        )
        style_rules_section = render_style_rules(
            state.strategy_gradients,
            language=preferred_language,
        )

        # Generate unique recommendation ID BEFORE triggering (so frontend can use it for feedback)
        # rec_id 加 uuid 后缀避免碰撞：纯毫秒时间戳在并发（cron 到点 + 手动"立即执行"
        # 同毫秒触发）或测试快速执行时可能重复，而 feedback_collector 按 rec_id 去重，
        # 重复 rec_id 会让第二条推荐的反馈被丢弃。
        rec_id = f"rec_{int(time.time() * 1000)}_{uuid.uuid4().hex[:8]}"

        def _on_delivered(generated_message: str = "") -> None:
            """后台送达后才执行的状态更新（Step 7）。

            重新 load 最新 state 再持久化——本回调在后台 task 真正跑完时才执行，
            距 tick 时载入的 ``state`` 快照可能已隔了一段时间。期间用户可能已发
            chat.send 触发隐式反馈写入 feedback_buffer（见 _try_record_implicit_feedback），
            或别的路径改过 state。若直接复用旧快照 save，会把中间的反馈/状态覆盖丢失。
            重新 load 拿到最新持久化态再 add_recommendation，与 buffer 消费各自独立
            load/save 的粒度一致。
            """
            from jiuwenswarm.agents.harness.common.recommendation.profile_extractor import (
                load_recommendation_state,
            )
            fresh_state = load_recommendation_state()
            _increment_daily_count()

            fresh_state.add_recommendation({
                "id": rec_id,
                "type": decision.type,
                "target": decision.target,
                "reason": decision.reason,
                "urgency": decision.urgency,
                "tick_at": time.time(),
                "session_id": target_session.session_id,
                "content": generated_message,  # LLM-generated recommendation text
            })
            fresh_state.touch()
            save_recommendation_state(fresh_state)
            logger.info("[ProactiveEngine] delivered '%s' (id=%s, type=%s, urgency=%.2f, session=%s)",
                         decision.target, rec_id, decision.type, decision.urgency,
                         target_session.session_id[:20])

        from jiuwenswarm.server.runtime.proactive_adapter import ProactiveTriggerRequest
        trigger_request = ProactiveTriggerRequest(
            session_id=target_session.session_id,
            decision=decision,
            channel_id=target_channel,
            on_delivered=_on_delivered,
            rec_id=rec_id,
            style_rules_section=style_rules_section,
        )
        triggered = await _trigger_main_agent(
            self._trigger_main_agent_callback,
            trigger_request,
        )
        if not triggered:
            logger.info("[ProactiveEngine] not triggered (session busy, duplicate inflight, "
                        "or trigger failed), skipping")
            self._last_tick_at = time.time()
            return False

        # 已 fire-and-forget 触发：立即返回，后台跑完会回调 _on_delivered 做计数。
        # cron 端不等主 agent，秒回不超时；_last_tick_at 立即更新让下次 tick 排程正常。
        self._last_tick_at = time.time()
        return True

    # ── Maintenance helpers (called by Cron or manually) ─────────

    @staticmethod
    def run_maintenance() -> None:
        """Prune stale daily counts.

        cooldown_records 已完全移除（字段/函数/常量），不再有读写，
        recommendation.json 不再有该键。daily_counts 仍由 tick 写（每日额度计数），
        需 prune 清掉老日期 key。
        """
        from jiuwenswarm.agents.harness.common.recommendation.proactive_actions import (
            _prune_daily_counts,
        )

        _prune_daily_counts()
        logger.debug("[ProactiveEngine] maintenance completed")
